services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bankingsystem-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "BankSys_2026!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - bankingsystem-data:/var/opt/mssql

volumes:
  bankingsystem-data:
